# This is a basic workflow to help you get started with Actions
name: Build and Publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  CI: true
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "22.x"
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install
        run: npm install
      - name: Build
        env:
          NODE_OPTIONS: ${{ env.NODE_OPTIONS }}
        run: npm run sync && npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
